### ISSUE TITLE
Can FlingOS run C# programs, like from .NET or Mono?

### ISSUE THREAD

**Issue by wind39** [FlingOS/FlingOS#36]
Sorry if the answer is in the documentation and I didn't noticed it.

Will I be able to compile a C# program against Mono, for example, and run it on FlingOS ?

**Comment by EdNutting** [comment]
Hi, no problem, it's not in the documentation. In short, no. And you are unlikely to ever be able to.

FlingOS is still developing its ABI and we have no intention of implementing the underside of the .NET Framework API. We're aiming at low-level education meaning drivers etc. not at creating a full C# system / ecosystem. Our long-term development aim is to develop sample drivers and a very-small sample user-mode layer with something like a basic web browser. We don't intend FlingOS to become a proper/full operating system in a commercial sense (i.e. not a rival to Linux, Windows, OSX or their derivatives). 

If you're looking to be able to write .NET-compatible apps at the OS level, take a look at the Cosmos project (though you still won't be able to compile against MS .Net or Mono - you will have to compile against their implementation of the framework).

**Comment by wind39** [comment]
@EdNutting Thank you! :+1:
