### ISSUE TITLE
-1 return values

### ISSUE THREAD

**Issue by EdNutting** [FlingOS/FlingOS#62]
## Background

The FlingOS kernel uses the number minus one (-1) as a return value in many places to indicate failure (often as "couldn't return a proper value so here's -1 instead"). Unfortunately, many of the callers of such functions do not bother checking the return value nor handling it if it is -1.

## What needs doing (1 of 2)

Someone needs to go through the code thoroughly to find all places where -1 is returned and record all the found places. This will involving searching for both:

```csharp
...
return -1;
...
```

and the following sort of pattern:

```csharp
...
int result = 0xA; // Some initial value, could be any number (including -1)
...               // The main body of the function follows
result = -1;      // At some point, the result gets set to -1.
...               // [More function body]
return result;    // Return the result
```

Note that `result` could be called anything. Common names include:

- result
- res
- resVal
- retVal
- returnVal

## What needs doing (2 of 2)

Once all the places where -1 is returned have been found, use "Find all references" to find all the callers of those methods, and create a list of the callers. For each caller, determine if it (or one of its direct callers) handles the -1 return value. For any case where the -1 return value isn't checked for / otherwise handled, create an issue (here in GitHub) describing the location i.e. file name, project/folder name and line number, along with an exact copy of the line code when it was found.

Copies of the code should take the line itself and 5 lines above and 5 lines below the line (counted excluding the line itself). This hopefully provides sufficient context for the line to be identified later even if the exact line number changes.

**Comment by rolandbaranyi** [comment]
I have searched through the project and I am fairly confident that the only unhandled -1 return values were in MassStorageDevice.
