### ISSUE TITLE
Trim functions non-standard

### ISSUE THREAD

**Issue by EdNutting** [FlingOS/FlingOS#63]
The Trim(), TrimStart() and TrimEnd() functions of FOS_System.String are non-standard. They only trim spaces " ". They should also trim things like new lines (\n), carriage returns (\r) and tabs (\t).

Add the characters listed [on this page](https://msdn.microsoft.com/en-us/library/t809ektx(v=vs.110).aspx) to ones searched for. Use the Unicode encodings for absolute certainty as to which are being removed.

**Comment by toothbrush7777777** [comment]
@rolandbaranyi Ping?

**Comment by EdNutting** [comment]
@toothbrush7777777 @rolandbaranyi Sorry for the delay on this - as you may have noticed, the codebase has been undergoing a transformation lately. 

Roland, please review this contribution from toothbrush777 - check out their version of the code, compile & test to see if it works and if so, we can approve the pull request.

Many thanks for your contribution - it will be reviewed within this week,
Ed

**Comment by toothbrush7777777** [comment]
@EdNutting No worries, I know the feeling

**Comment by EdNutting** [comment]
Merged! 7fcd1be
