### ISSUE TITLE
Type or namespace could not be found.

### ISSUE THREAD

**Issue by rolandbaranyi** [FlingOS/FlingOS#71]
in 'Kernel.Debug.Debugger.MainForm' at line 254, 'MarkerStyle' and 'FastColoredTextBoxNS' gives the above error.

        }

        int oldCurrCSLineHighlightStartPos = -1;
        int oldCurrCSLineHighlightEndPos = -1;
        MarkerStyle CurrCSLineStyle = new FastColoredTextBoxNS.MarkerStyle(Brushes.Pink);
        private void ReloadCSText()
        {
            if (this.InvokeRequired)
            {
                this.Invoke(new VoidDelegate(ReloadCSText));

**Comment by EdNutting** [comment]
This is expected as the old Debugger is now deprecated and won't build. We will be implementing a new one in the near future.
