### ISSUE TITLE
A lot of errors trying to "build" the solution on VS2013

### ISSUE THREAD

**Issue by lcnvdl** [FlingOS/FlingOS#83]
I'm trying to "Build" the solution of your FlingOS in Visual Studio, for x86 platform and for "Any platform" but I get a lot of errors:

Error	290	Unable to copy file "obj\x86\Debug\FlingOops.dll" to "bin\Debug\FlingOops.dll". The process cannot access the file 'bin\Debug\FlingOops.dll' because it is being used by another process.	FlingOops
Error	1623	Unable to copy file "C:\Users\User\git\rodar\Drivers\Compiler\bin\Debug\Drivers.Compiler.dll" to "bin\Debug\Drivers.Compiler.dll". The process cannot access the file 'bin\Debug\Drivers.Compiler.dll' because it is being used by another process.	Drivers.Compiler.MSBuildTask
Error	1611	Unable to copy file "C:\Users\User\git\rodar\Drivers\Compiler\Architectures\x86_32\bin\Debug\Drivers.Compiler.Architectures.x86.dll" to "bin\Debug\Drivers.Compiler.Architectures.x86.dll". The process cannot access the file 'bin\Debug\Drivers.Compiler.Architectures.x86.dll' because it is being used by another process.	Drivers.Compiler.MSBuildTask
Error	1599	Unable to copy file "C:\Users\User\git\rodar\Drivers\Compiler\App\bin\Debug\Drivers.Compiler.App.exe" to "bin\Debug\Drivers.Compiler.App.exe". The process cannot access the file 'bin\Debug\Drivers.Compiler.App.exe' because it is being used by another process.	Drivers.Compiler.MSBuildTask
Error	1945	The "MSBuildTask.BuildTask" task could not be loaded from the assembly C:\Users\User\git\rodar\Drivers\Compiler\MSBuildTask\bin\Debug\Drivers.Compiler.MSBuildTask.dll. Could not load file or assembly 'file:///C:\Users\User\git\rodar\Drivers\Compiler\MSBuildTask\bin\Debug\Drivers.Compiler.MSBuildTask.dll' or one of its dependencies. El sistema no puede encontrar el archivo especificado. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.	C:\Users\User\git\rodar\Kernel\Kernel\Kernel.csproj	175	5	Kernel (Kernel\Kernel)
Error	1	Invalid options supplied. Could not find tools directory! Tools Path argument is invalid.	C:\Users\User\git\rodar\Drivers\TestDriver\TestDriver.csproj	131	5	TestDriver
Error	289	Could not copy "obj\x86\Debug\FlingOops.dll" to "bin\Debug\FlingOops.dll". Exceeded retry count of 10. Failed.	FlingOops
Error	1622	Could not copy "C:\Users\User\git\rodar\Drivers\Compiler\bin\Debug\Drivers.Compiler.dll" to "bin\Debug\Drivers.Compiler.dll". Exceeded retry count of 10. Failed.	Drivers.Compiler.MSBuildTask
Error	1610	Could not copy "C:\Users\User\git\rodar\Drivers\Compiler\Architectures\x86_32\bin\Debug\Drivers.Compiler.Architectures.x86.dll" to "bin\Debug\Drivers.Compiler.Architectures.x86.dll". Exceeded retry count of 10. Failed.	Drivers.Compiler.MSBuildTask
Error	1598	Could not copy "C:\Users\User\git\rodar\Drivers\Compiler\App\bin\Debug\Drivers.Compiler.App.exe" to "bin\Debug\Drivers.Compiler.App.exe". Exceeded retry count of 10. Failed.	Drivers.Compiler.MSBuildTask

**Comment by EdNutting** [comment]
Please follow the [Setup for development guide](http://flingos.co.uk/docs/reference/FlingOS/). Specifically, you need to set the "MSBUILDNONODEREUSE" environment variable to prevent these errors occurring. You will also need to use Debug|x86 not Debug|Any for the build to succeed.

Cheers,
Ed
